---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: ${CSI_NAMESPACE}
stringData:
  # Required for statically provisioned volumes
  userID: <plaintext ID>
  userKey: <Ceph auth key corresponding to ID above>

  # Required for dynamically provisioned volumes
  adminID: <plaintext ID>
  adminKey: <Ceph auth key corresponding to ID above>
