apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-host-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/etc/kubernetes"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-host-pvc
spec:
  storageClassName: manual
  volumeName: test-host-pv #
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---  
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  volumes:
    - name: test-pv-storage
      persistentVolumeClaim:
        claimName: test-host-pvc
  containers:
    - name: test-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/mnt/k8s"
          name: test-pv-storage


