apiVersion: v1
kind: Pod
metadata:
  name: test-pipeline-secret
spec:
  containers:
    - name: test-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - name: pipeline-secret
          mountPath: "/etc/pipeline-secret"
          readOnly: true
  volumes:
    - name: pipeline-secret
      secret:
        secretName: aro-pipeline-secret