apiVersion: v1
kind: PersistentVolume
metadata:
  name:  pki-tls-ca-cnf-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/etc/pki"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  pki-tls-ca-cnf-pvc
spec:
  storageClassName: manual
  volumeName:  pki-tls-ca-cnf-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---  
apiVersion: v1
kind: Pod
metadata:
  name: pki-tls-ca-cnf-pod
spec:
  volumes:
    - name: test-pv-storage
      persistentVolumeClaim:
        claimName:  pki-tls-ca-cnf-pvc
  containers:
    - name: pki-cnf
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/mnt/pki"
          name: test-pv-storage


