apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pki-tls-ca-root-ds
  namespace: default
  labels:
    k8s-app: pki-tls-ca-root
spec:
  selector:
    matchLabels:
      name: pki-tls-ca-root
  template:
    metadata:
      labels:
        name: pki-tls-ca-root
    spec:
      tolerations:
      - key: node-role.kubernetes.io/worker
        effect: NoSchedule
      securityContext:
      runAsUser: 0
      runAsGroup: 0
      volumes:
      - name: test-pv-storage
        persistentVolumeClaim:
          claimName:  root-storage-pvc
      containers:
      - name: pki-cnf
        image: nginx
        command:
          - "/bin/sh"
          - "-c"
          - while true; do wget https://raw.githubusercontent.com/ezYakaEagle442/aro-pub-storage/master/cnf/DigiCert_SHA2_Secure_Server_CA.cer; sleep 86400; done        
        ports:
          - containerPort: 80
            name: "http-server"
        volumeMounts:
          - mountPath: "/mnt/root"
            name: test-pv-storage
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: false