apiVersion: v1
kind: PersistentVolume
metadata:
  name: root-storage-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: root-storage-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---  
apiVersion: v1
kind: Pod
metadata:
  name: root-storage-pod
spec:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  volumes:
    - name: root-storage-pv-storage
      persistentVolumeClaim:
        claimName: root-storage-pvc
  containers:
    - name: test-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/mnt/root"
          name: root-storage-pv-storage
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
        readOnlyRootFilesystem: false

